#!/bin/bash
echo "Setting up Python configuration files..."

# Create a persistent user Python environment using uv
echo "Setting up user Python environment..."
echo "Setting up Python configuration files..."

# Create a persistent user Python environment using uv
echo "Setting up user Python environment..."
USER_VENV="${HOME}/.local/pipenv-global"
ACTIVATE_DIR="${HOME}/.local/bin"
ACTIVATE_SCRIPT="${ACTIVATE_DIR}/activate-pipenv-global"

# Only proceed if uv is available
if command -v uv > /dev/null 2>&1; then
    echo "Creating global environment at $USER_VENV..."
    # Remove any existing environment to ensure clean setup
    rm -rf "$USER_VENV"
    mkdir -p "$USER_VENV"
    
    # Create virtual environment with uv
    uv venv -p 3.11 "$USER_VENV"
    
    if [ -f "${USER_VENV}/bin/python" ]; then
        echo "Installing essential packages in user environment..."
        # Install core packages with uv for consistency
        "${USER_VENV}/bin/python" -m pip install wheel setuptools virtualenv awscli
        
        # Create activation script
        mkdir -p "$ACTIVATE_DIR"
        echo "# Auto-generated by dotfiles setup" >> "$ACTIVATE_SCRIPT"
        echo "source \"${USER_VENV}/bin/activate\"" >> "$ACTIVATE_SCRIPT"
        chmod +x "$ACTIVATE_SCRIPT"
        
        echo "Created activation script at $ACTIVATE_SCRIPT"
    else
        echo "Failed to create virtual environment. Please check uv installation."
    fi
else
    echo "WARNING: uv not found, skipping global Python environment setup."
    echo "Please install uv manually and run 'just link-python-config' after installation."
fi
